---
- name: stop instance
  hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
      aws_region: "us-west-1"
      instance_id: "i-0b0cb236ffe0fbbc3"

  tasks:
    - name: stop ec2
      ec2:
        instance_ids: "{{ instance_id }}"
        region: "{{ aws_region }}"
        state: stopped
        wait: true

    - name: get instance status
      ec2_instance_facts:
        region: "{{ aws_region }}"
        instance_ids: 
          - "{{ instance_id }}"
      register: ec2

    - name: display ec2 status
      debug:
        msg:
          - "##################################################"
          - "{{ ec2.instances[0].state}}"
          - "##################################################" 
