---
- name: start instance
  hosts: localhost
  connection: local
  gather_facts: false
    
  vars:
      aws_region: "us-west-1"
      instance_id: "i-0b0cb236ffe0fbbc3"

  tasks:
    - name: start ec2
      ec2:
        instance_ids: "{{ instance_id }}"
        region: "{{ aws_region }}"
        state: running
        wait: true

    - name: get instance status
      ec2_instance_facts:
        region: "{{ aws_region }}"
        instance_ids: 
          - "{{ instance_id }}"
      register: ec2 

    - name: wait for ssh to come up
      wait_for:
        host: "{{ ec2.instances[0].public_ip_address }}"
        port: 22
        delay: 30
      tags:
        - wait

    - name: display ec2 status
      debug:
        msg:
          - "##################################################"
          - "{{ ec2.instances[0].state}}"
          - "##################################################" 
