---
- name: use template module to setup service manager's config
  hosts: serm1
  gather_facts: false
  vars:
    mqtt_ip: ns001.dropap.com
    mqtt_port: 80
    mec_ip: mec001.dropap.com
    mec_port: 50000
    redis_ip: mec-redis001.dropap.com
    redis_port: 6379
    redis_password: 12345678
    couchbase_host: coredb001.dropap.com
    relay_ip: rs001.dropap.com
    relay_port: 80
    elasticsearch_ip: 172.31.2.229

  tasks:
    - name: generate the service manager config file
      template:
        src: templates/config.js.j2
        dest: /home/hank_chen/blazing_sm_20171121/sm_dev/serMgr/config.js
        owner: hank_chen
        group: hank_chen
        mode: 0755
        backup: yes
