---
- name: Fetch server info
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
      aws_region: "us-west-1"
      redis_instance_id: "i-046254f80e3cf985b"
      ns_instance_id: "i-0eb0d9d7940242f4c"
      mec_instance_id: "i-07076ccce4c4ef7a0"
      rs_instance_id: "i-04f0f95eb15de1425"

  tasks:
    - import_tasks: get_redis_info.yml
    - import_tasks: get_ns_info.yml
    - import_tasks: get_mec_info.yml
    - import_tasks: get_rs_info.yml

- name: use template module to setup service manager's config
  hosts: serm1
  gather_facts: false
  vars:
    mqtt_ip: "{{ hostvars.localhost.ns_public_ip }}"
    mqtt_port: 80
    mec_ip: "{{ hostvars.localhost.mec_public_ip }}"
    mec_port: 50000
    redis_ip: "{{ hostvars.localhost.redis_private_ip }}"
    redis_port: 6379
    redis_password: 12345678
    couchbase_host: coredb001.dropap.com
    relay_ip: "{{ hostvars.localhost.rs_public_ip }}"
    relay_port: 80
    elasticsearch_ip: 172.31.2.229
    user: "hank_chen"
    config_path: "blazing_sm_20171121"

  tasks:
    - debug:
        msg:
          - "#######################################################"
          - "[var] mqtt_ip: {{ mqtt_ip }}"
          - "[var] mec_ip: {{ mec_ip }}"
          - "[var] redis_ip: {{ redis_ip }}"
          - "[var] relay_ip: {{ relay_ip }}"
          - "#######################################################"
    - name: generate the service manager config file
      template:
        src: templates/config.js.j2
        dest: "/home/{{ user }}/{{ config_path }}/sm_dev/serMgr/config.js"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755
        backup: yes
