---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
      aws_region: "us-west-1"
      redis_instance_id: "i-046254f80e3cf985b"

  tasks:
    - import_tasks: get_redis_info.yml

- name: use the template module to setup mosquitto config file 
  hosts: ns
  gather_facts: false
  vars:
     redis_db_ip: "{{ hostvars.localhost.redis_private_ip }}"
     redis_db_port: 6379
     redis_db_password: 12345678

  tasks:
    - debug:
        msg:
          - "#######################################################"
          - "[var] redis_db_ip: {{ redis_db_ip }}"
          - "#######################################################"
    - name: generate the mosquitto config file
      template:
        src: templates/mosquitto.conf.j2
        dest: /etc/mosquitto/mosquitto.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
