---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
      aws_region: "us-west-1"
      redis_instance_id: "i-046254f80e3cf985b"
      ns_instance_id: "i-0eb0d9d7940242f4c"

  tasks:
    - import_tasks: get_redis_info.yml
    - import_tasks: get_ns_info.yml

- name: use the lineinfile module to setup mec and mqtt config files 
  hosts: mec 
  gather_facts: false
  vars:
     redis_db_ip: "{{ hostvars.localhost.redis_private_ip }}" 
     redis_db_port: 6379
     redis_db_auth: 12345678
     mec_mqtt_account: su_MEC-A
     mec_mqtt_password: 12345678
     mqtt_private_ip: "{{ hostvars.localhost.ns_private_ip }}"
     mqtt_public_ip: "{{ hostvars.localhost.ns_public_ip }}"
     user: "hank_chen"
     config_path: "mec_release_20160201"

  tasks:
    - debug:
        msg:
          - "########################################################"
          - "[var] redis_db_ip: {{ redis_db_ip }}"
          - "[var] mqtt_private_ip: {{ mqtt_private_ip }}"
          - "[var] mqtt_public_ip: {{ mqtt_public_ip }}"
          - "########################################################"
    - name: mec config - redis.host
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mec.conf"
        regexp: 'redis\.host\s*='
        line: "redis.host = {{ redis_db_ip }}"
        state: present
        backup: yes

    - name: mec config - redis.port
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mec.conf"
        regexp: 'redis\.port\s*='
        line: "redis.port = {{ redis_db_port }}"
        state: present
        backup: yes

    - name: mec config - redis.auth
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mec.conf"
        regexp: 'redis\.auth\s*='
        line: "redis.auth = {{ redis_db_auth }}"
        state: present
        backup: yes

    - name: mec config - mec.mqtt.account 
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mec.conf"
        regexp: 'mec\.mqtt\.account\s*='
        line: "mec.mqtt.account = {{ mec_mqtt_account }} # physical MEC's username/clientid, use to connect to mosquitto"
        state: present
        backup: yes

    - name: mec config - mec.mqtt.password 
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mec.conf"
        regexp: 'mec\.mqtt\.password\s*='
        line: "mec.mqtt.password = {{ mec_mqtt_password }} # MEC's password"
        state: present

    - name: mqtt config - mosquitto2
      lineinfile:
        path: "/home/{{ user }}/{{ config_path }}/mec/config/mqtt.conf"
        regexp: 'mosquitto2\s*='
        line: "mosquitto2 = {{ mqtt_private_ip }}:80/{{ mqtt_public_ip }}:80/1"
        state: present
        backup: yes
    - name: restart service
      shell: "/bin/bash /home/{{ user }}/{{ config_path }}/mec/monitor_mec.sh"
